In [1]:
import pandas as pd
import argparse
from icecream import ic

In [31]:
PATH = "Phage_data/"

df_meta = pd.read_excel(PATH+"VMR_MSL41.v1.20260320.xlsx", index_col = 23)

df_meta.head()

,Isolate ID,Species Sort,Isolate Sort,Realm,Subrealm,Kingdom,Subkingdom,Phylum,Subphylum,Class,...,Species,ICTV_ID,Exemplar or additional isolate,Virus name(s),Virus name abbreviation(s),Virus isolate designation,Genome coverage,Genome,Host source,Accessions Link
Accession,,,,,,,,,,,,,,,,,,,,,
PP467602,VMR1028127,1,1,Adnaviria,NaN,Zilligvirae,NaN,Taleaviricota,NaN,Tokiviricetes,...,Wargodvirus xiongnu,ICTV202420188,E,Bathyarchaeia bifangarchaeales chiyouvirus 1,BbCV1,NaN,Complete genome,dsDNA,archaea,NCBI Nucleotide
MH447526,VMR1000002,2,1,Adnaviria,NaN,Zilligvirae,NaN,Taleaviricota,NaN,Tokiviricetes,...,Alphalipothrixvirus beppuense,ICTV201908643,E,Sulfolobus filamentous virus 1,SFV1,S48,Complete genome,dsDNA,archaea,NCBI Nucleotide
MK064563,VMR1000001,3,1,Adnaviria,NaN,Zilligvirae,NaN,Taleaviricota,NaN,Tokiviricetes,...,Alphalipothrixvirus umijigokuense,ICTV201908644,E,Sulfolobales Beppu filamentous virus 2,SBFV2,clone B,Coding-complete genome,dsDNA,archaea,NCBI Nucleotide
AM087120,VMR1000003,4,1,Adnaviria,NaN,Zilligvirae,NaN,Taleaviricota,NaN,Tokiviricetes,...,Betalipothrixvirus acidiani,ICTV20094000,E,Acidianus filamentous virus 3,AFV3,NaN,Complete genome,dsDNA,archaea,NCBI Nucleotide
AF440571,VMR1000008,5,1,Adnaviria,NaN,Zilligvirae,NaN,Taleaviricota,NaN,Tokiviricetes,...,Betalipothrixvirus hveragerdiense,ICTV20041365,E,Sulfolobus islandicus filamentous virus,SIFV,NaN,Complete genome,dsDNA,archaea,NCBI Nucleotide

In [9]:
ic(df_meta.at["PP467602","Genus"])

Wargodvirus

In [15]:
df_phages = pd.read_csv(PATH+"7Apr2026_millardlab_website_table.tsv", sep = "\t")

df_phages.head()

,Accession,Description,Genome Length (KB),molGC (%),Genus,Sub-family,Family,Host
0,"<a href=""https://www.ncbi.nlm.nih.gov/nuccore/...",Salmonella phage SopEPhi,35,51,Felsduovirus,Unclassified,Peduoviridae,Salmonella
1,"<a href=""https://www.ncbi.nlm.nih.gov/nuccore/...",Escherichia phage H8,104,39,Tequintavirus,Markadamsvirinae,Demerecviridae,Escherichia
2,"<a href=""https://www.ncbi.nlm.nih.gov/nuccore/...",Escherichia phage vB_EcoP_24B,58,50,Traversvirus,Unclassified,Unclassified,Escherichia
3,"<a href=""https://www.ncbi.nlm.nih.gov/nuccore/...",Synechococcus phage S-CBP3,47,47,Lirvirus,Unclassified,Unclassified,Synechococcus
4,"<a href=""https://www.ncbi.nlm.nih.gov/nuccore/...",Salmonella phage pST_PMR_01::LL37,173,35,Unclassified,Unclassified,Unclassified,Salmonella

In [12]:
len('<a href="https://www.ncbi.nlm.nih.gov/nuccore/AY319521">')

56

In [16]:
## Trim the Accession
def trim(x):
    x = x[56:-4]
    return x
df_phages["Accession"] = df_phages["Accession"].apply(trim)

In [21]:
df_phages.head()

,Description,Genome Length (KB),molGC (%),Genus,Sub-family,Family,Host
Accession,,,,,,,
AY319521,Salmonella phage SopEPhi,35,51,Felsduovirus,Unclassified,Peduoviridae,Salmonella
AC171169,Escherichia phage H8,104,39,Tequintavirus,Markadamsvirinae,Demerecviridae,Escherichia
HM208303,Escherichia phage vB_EcoP_24B,58,50,Traversvirus,Unclassified,Unclassified,Escherichia
HQ633062,Synechococcus phage S-CBP3,47,47,Lirvirus,Unclassified,Unclassified,Synechococcus
PX574388,Salmonella phage pST_PMR_01::LL37,173,35,Unclassified,Unclassified,Unclassified,Salmonella

In [20]:
df_phages.set_index("Accession", inplace=True)

KeyError: "None of ['Accession'] are in the columns"

In [24]:
ic(df_phages.at["AY319521","Genome Length (KB)"])

ic| df_phages.at["AY319521","Genome Length (KB)"]: np.int64(35)

np.int64(35)

In [32]:
## Filter metadata for bacteriophages that are dsDNA

subset = df_meta[(df_meta["Genome"] == "dsDNA") & (df_meta["Host source"] == "bacteria")]

subset = subset["Genome"]
subset.head()

Accession
PP079415    dsDNA
MW960043    dsDNA
MT951568    dsDNA
KF626666    dsDNA
MZ326858    dsDNA
Name: Genome, dtype: object

In [38]:
subset.shape

(6367,)

In [35]:
comb_df = pd.merge(subset, df_phages, how = "inner", on = "Accession")

In [36]:
comb_df.head()

,Genome,Description,Genome Length (KB),molGC (%),Genus,Sub-family,Family,Host
Accession,,,,,,,,
PP079415,dsDNA,Xanthomonas phage SB4,44,58,Ceskevirus,Gujervirinae,Autonotataviridae,Xanthomonas
MW960043,dsDNA,Stenotrophomonas phage BUCT609,43,58,Maltophvirus,Gujervirinae,Autonotataviridae,Stenotrophomonas
MT951568,dsDNA,Xanthomonas phage Xaa_vB_phi31,43,60,Pazvirus,Gujervirinae,Autonotataviridae,Xanthomonas
KF626666,dsDNA,Xylella phage Paz,44,60,Pazvirus,Gujervirinae,Autonotataviridae,Xylella
MZ326858,dsDNA,Stenotrophomonas phage Pepon,43,60,Ponderosavirus,Gujervirinae,Autonotataviridae,Stenotrophomonas

In [37]:
comb_df.shape

(6037, 8)

In [39]:
for col in comb_df.columns:
    print(col, comb_df[col].value_counts().count())

Genome 1
Description 6030
Genome Length (KB) 271
molGC (%) 49
Genus 1612
Sub-family 76
Family 77
Host 161

In [49]:
genus_names = comb_df["Genus"].unique()
out_df = []
for g in genus_names:
    g_sub = comb_df[(comb_df["Genus"] == g)]
    med = g_sub["Genome Length (KB)"].median()
    m = g_sub["Genome Length (KB)"].min()
    mx = g_sub["Genome Length (KB)"].max()
    med_GC = g_sub["molGC (%)"].median()
    m_GC = g_sub["molGC (%)"].min()
    mx_GC = g_sub["molGC (%)"].max()
    s = g_sub.value_counts().count()
    d = {
        "Genus": g,
        "Median Genome Length (KB)": med,
        "Min Genome Length (KB)": m,
        "Max Genome Length (KB)": mx,
        "Median molGC (%)": med_GC,
        "Min molGC (%)": m_GC,
        "Max molGC (%)": mx_GC,
        "Sample Size": s
    }
    out_df.append(d)
out_df = pd.DataFrame(out_df)

In [51]:
out_df.sort_values(["Sample Size"], ascending=[False]).head()

,Genus,Median Genome Length (KB),Min Genome Length (KB),Max Genome Length (KB),Median molGC (%),Min molGC (%),Max molGC (%),Sample Size
57,Unclassified,46.0,33,300,46.0,25,70,218
127,Przondovirus,41.0,37,42,53.0,51,53,131
939,Cheoctovirus,58.0,52,61,61.0,61,62,106
523,Webervirus,50.0,38,54,51.0,48,52,100
56,Drulisvirus,44.0,39,49,54.0,39,55,98

In [53]:
out_df.to_csv("1612_phage_genome_stats.tsv",index = False, sep = "\t")